# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/lingmo/extra/lingmo-calendar/calendar/lingmowebviewdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LingmoWebviewDialog(object):
    def setupUi(self, LingmoWebviewDialog):
        LingmoWebviewDialog.setObjectName("LingmoWebviewDialog")
        LingmoWebviewDialog.resize(400, 300)

        self.retranslateUi(LingmoWebviewDialog)
        QtCore.QMetaObject.connectSlotsByName(LingmoWebviewDialog)

    def retranslateUi(self, LingmoWebviewDialog):
        _translate = QtCore.QCoreApplication.translate
        LingmoWebviewDialog.setWindowTitle(_translate("LingmoWebviewDialog", "Dialog"))
